[package]

name = "persistent"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
version = "0.1.0"
readme = "README.md"
tags = ["web", "server", "middleware", "iron", "core", "persistent"]

[[lib]]

name = "persistent"
path = "src/lib.rs"

[dependencies.iron]

git = "https://github.com/iron/iron.git"

