[package]

name = "persistent"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
version = "0.1.0"

[lib]

name = "persistent"
path = "src/lib.rs"

[dependencies.iron]

git = "https://github.com/iron/iron.git"

[dependencies.typemap]

git = "https://github.com/reem/rust-typemap.git"

[dependencies.plugin]

git = "https://github.com/reem/rust-plugin.git"

